### ISSUE TITLE
Any seeds running?

### ISSUE THREAD

**Issue by faddat** [ethanfrey/signedpost#1]

**Comment by ethanfrey** [comment]
Hi Jakob,

This code is not deployed yet. It is more for devs right now. You can run
locally and use signedpost-react to provide a ui.

I hope to bring it to a point where it can e deployed with a couple seeds
by the end of December, or early January. But rather far from production
use.

You can follow this issue and I will update it when there are seeds running.

**Comment by faddat** [comment]
I'm doing some similar stuff:

GitHub.com/baabeetaa/glogchain

I will be moving the repo and a bunch of related stuff later today, but I
am interested in conversation and collaboration.  My interest now is in
learning well how to manage hard forks and similar issues stemming from
software updates using tendermint.

**Comment by ethanfrey** [comment]
Sounds interesting. I am on vacation now, and get home in 2 weeks. I'll
take a deeper look then. But I would definitely like to discuss idea and
share code on these issues.

My first step was getting an API that could be used by normal web ready
clients. Then I am looking into "light clients" validating the data they
receive. I have ideas and would love to discuss.

Then also handling harder cases like migrating versions, recovering from
hard forks (majority Byzantine), etc....

I'll drop you a note when I am back.

Cheers,
Ethan

Btw, I took a 2 minute look at your repo and saw no reference to
tendermint. Are you using it yet, or planning to? There is also a nice
slack group that will answer many questions. Check out the homepage for the
link.
